
<script>
(() => {
    // List of images with URLs
    const images_list = [

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-00.jpeg",
        "alt": "",
        "name": "step-00.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-01.jpeg",
        "alt": "",
        "name": "step-01.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-02.jpeg",
        "alt": "",
        "name": "step-02.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-03.jpeg",
        "alt": "",
        "name": "step-03.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-04.jpeg",
        "alt": "",
        "name": "step-04.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-05.jpeg",
        "alt": "",
        "name": "step-05.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-06.jpeg",
        "alt": "",
        "name": "step-06.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-07.jpeg",
        "alt": "",
        "name": "step-07.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-08.jpeg",
        "alt": "",
        "name": "step-08.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-09.jpeg",
        "alt": "",
        "name": "step-09.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-10.jpeg",
        "alt": "",
        "name": "step-10.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-11.jpeg",
        "alt": "",
        "name": "step-11.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-12.jpeg",
        "alt": "",
        "name": "step-12.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-13.jpeg",
        "alt": "",
        "name": "step-13.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-14.jpeg",
        "alt": "",
        "name": "step-14.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-15.jpeg",
        "alt": "",
        "name": "step-15.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-16.jpeg",
        "alt": "",
        "name": "step-16.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-17.jpeg",
        "alt": "",
        "name": "step-17.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-18.jpeg",
        "alt": "",
        "name": "step-18.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-19.jpeg",
        "alt": "",
        "name": "step-19.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-20.jpeg",
        "alt": "",
        "name": "step-20.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-21.jpeg",
        "alt": "",
        "name": "step-21.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-22.jpeg",
        "alt": "",
        "name": "step-22.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step-23.jpeg",
        "alt": "",
        "name": "step-23.jpeg",
        "link": ""
    },

    {
        "url": "https://michaelwoodc.github.io/IT_Infrastructure_2/xampp_installation/step.stg",
        "alt": "",
        "name": "step.stg",
        "link": ""
    }
    ];

    // Generated by https://www.html-code-generator.com/html/image-slideshow-generator
    let slider_id = document.querySelector("#hcg-slider-1");

    // Append all images
    let dots_div = "";
    let images_div = "";
    for (let i = 0; i < images_list.length; i++) {
        // if no link without href="" tag
        let href = (images_list[i].link == "" ? "":' href="'+images_list[i].link+'"');
        images_div += '<a'+href+' class="hcg-slides animated"'+(i === 0 ? ' style="display:flex"':'')+'>'+
                        '<span class="hcg-slide-number">'+(i+1)+'/'+images_list.length+'</span>'+
                        '<img src="'+images_list[i].url+'" alt="'+images_list[i].name+'">'+
                        '<span class="hcg-slide-text">'+images_list[i].name+'</span>'+
                     '</a>';
        dots_div += '<a href="#" class="hcg-slide-dot'+(i === 0 ? ' dot-active':'')+'" data-id="'+i+'"></a>';
    }
    slider_id.querySelector(".hcg-slider-body").innerHTML = images_div;
    slider_id.querySelector(".hcg-slide-dot-control").innerHTML = dots_div;

    let slide_index = 0;

    const images = slider_id.querySelectorAll(".hcg-slides");
    const dots = slider_id.querySelectorAll(".hcg-slide-dot");
    const prev_button = slider_id.querySelector("#hcg-slide-prev");
    const next_button = slider_id.querySelector("#hcg-slide-next");

    const showSlides = () => {
        if (slide_index > images.length-1) {
            slide_index = 0;
        }
        if (slide_index < 0) {
            slide_index = images.length-1;
        }
        for (let i = 0; i < images.length; i++) {
            images[i].style.display = "none";
            dots[i].classList.remove("dot-active");
            if (i == slide_index) {
                images[i].style.display = "flex";
                dots[i].classList.add("dot-active");
            }
        }
    }

    prev_button.addEventListener("click", event => {
        event.preventDefault();
        slide_index--;
        showSlides();
    }, false);

    next_button.addEventListener("click", event => {
        event.preventDefault();
        slide_index++;
        showSlides();
    }, false);

    const dot_click = event => {
        event.preventDefault();
        slide_index = event.target.dataset.id;
        showSlides();
    }

    for (let i = 0; i < dots.length; i++) {
        dots[i].addEventListener("click", dot_click, false);
    }
})();
</script>
